color: null
fieldLayouts:
  a70a5bb4-2def-4e0e-a7ea-695b5ed884f2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-07T10:00:49+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8a5f169c-2faf-40a8-bb79-d61bfc3e3942
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T10:00:49+02:00'
            elementCondition: null
            fieldUid: 7df417e8-1eea-46d8-85a7-2a20370a881e # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d5309b4-c726-40b9-a00e-2880f8a20b80
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T10:00:49+02:00'
            elementCondition: null
            fieldUid: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce1b9abb-61e9-4815-8486-a3bc9063ed09
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T10:00:49+02:00'
            elementCondition: null
            fieldUid: 8cdefc82-9e0e-4dae-8feb-1609c6c9873b # Single Line Text
            handle: wideContent
            includeInCards: false
            instructions: 'Whether this page will use a wider screen size'
            label: 'Wide Content'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e8dc987-ad17-4787-b976-35a0915861d5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c2a690a1-0974-4138-89aa-ec3f8ba85385
        userCondition: null
handle: articlesIndex
hasTitleField: true
icon: id-card
name: 'Articles Index'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: language
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
