color: null
fieldLayouts:
  902cb6e1-33ee-4b4e-9696-3eadcee468a9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T11:35:30+01:00'
            elementCondition: null
            template: _cp/drafts
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: ec6857b8-375f-4503-8c91-ac18df77235e
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-13T11:35:30+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fe253e4e-b6e6-4e47-964e-3d2aad9c35f2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:35:30+01:00'
            elementCondition: null
            fieldUid: 489638d6-dd95-43c0-a6cd-cca5a8898feb # Toggle
            handle: featured
            includeInCards: false
            instructions: 'The article will stick to top on the home page and in the article index. Mark just one or two articles!'
            label: Featured
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bf36a6b-c859-40b1-9417-477d656bb0dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:35:30+01:00'
            elementCondition: null
            fieldUid: 7df417e8-1eea-46d8-85a7-2a20370a881e # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b64aa39-6335-4793-9938-c8fb7e109cbb
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-13T11:35:30+01:00'
            elementCondition: null
            fieldUid: 087d6426-bc8d-4c44-b207-23dd11d11345 # Topics
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7568e4b2-2c2c-49e0-b309-913d2b4224af
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:35:30+01:00'
            elementCondition: null
            fieldUid: 992f51d0-e22b-4c12-a6ba-d098fa334cd3 # Related Entries
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbfcfd78-d08f-441c-8b8c-9ac8556e13b8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:35:30+01:00'
            elementCondition: null
            fieldUid: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
            handle: null
            includeInCards: false
            instructions: null
            label: Content
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df0d7bce-2322-495f-8f41-5d7b87596331
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7df95195-2e58-4351-9695-13247cc8839d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T11:35:30+01:00'
            elementCondition: null
            template: _cp/local-images
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: c03ef924-c64d-4fb4-9509-0687e16b9cc6
            userCondition: null
            width: 100
          -
            dateAdded: '2024-11-13T11:35:30+01:00'
            elementCondition: null
            template: _cp/related-entries
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: 9cc0a276-a1cf-4c5e-953c-020e72a6d5be
            userCondition: null
            width: 100
        name: Info
        uid: 33ee5cf5-2545-423b-8fa2-e4ae0608171a
        userCondition: null
handle: article
hasTitleField: true
icon: newspaper
name: Article
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: language
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
