color: null
fieldLayouts:
  4ef852ec-ff8c-4d13-8534-084a50028adc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-08T09:21:30+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 56e24a94-46b6-47a5-870a-3ddee6b1e101
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-08T09:21:30+02:00'
            elementCondition: null
            fieldUid: 7df417e8-1eea-46d8-85a7-2a20370a881e # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad413a2b-b747-4dc0-b0c7-e987b805faf6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-08T09:21:30+02:00'
            elementCondition: null
            fieldUid: 8f7d3ebf-f42d-4024-aeae-1fad436fd93c # Home Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 752c9741-de15-4cde-b128-f4fef726b814
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 759084df-ecc1-40e7-8bfd-3a68b51a6ba6
        userCondition: null
handle: defaultHome
hasTitleField: true
icon: house
name: 'Default Site Home'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: language
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: language
