color: null
fieldLayouts:
  22cc67d9-e2e7-4e8d-b385-a1bc4c43835e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4b050685-0425-4094-bde2-85e2eedd0e12
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5f31ac1-d94c-4311-82fa-1ef9ce42f581
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: a00e6fe6-6460-422d-b845-67c760aa1651
            handle: null
            includeInCards: false
            instructions: null
            label: Level
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa86aa14-6f7b-40cc-80f3-f615590ffac3
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: be6789a7-64de-4d8d-a3a8-38a75763af9b
        userCondition: null
handle: heading
hasTitleField: false
icon: null
name: Heading
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
