color: null
fieldLayouts:
  22cc67d9-e2e7-4e8d-b385-a1bc4c43835e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-05T12:03:03+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 728f6879-714e-4f0d-9583-cc98276510b1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-05T12:03:03+01:00'
            elementCondition: null
            fieldUid: 8cdefc82-9e0e-4dae-8feb-1609c6c9873b # Single Line Text
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1dcd098-fb7d-4441-8772-72184789fafb
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-01-05T12:03:03+01:00'
            elementCondition: null
            fieldUid: a00e6fe6-6460-422d-b845-67c760aa1651 # Heading  Level
            handle: null
            includeInCards: false
            instructions: null
            label: Level
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa86aa14-6f7b-40cc-80f3-f615590ffac3
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: be6789a7-64de-4d8d-a3a8-38a75763af9b
        userCondition: null
handle: heading
hasTitleField: false
icon: text
name: Heading
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
