color: null
fieldLayouts:
  abb633b6-3f52-4939-b871-3ea1ca602a5a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-08T09:21:30+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d9b8dacd-ca19-4b4d-89a7-5a0dc5587665
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-08T09:21:30+02:00'
            elementCondition: null
            fieldUid: a75bc4db-f149-453d-9972-1c3685ec1b1d # Featured Image By Site
            handle: null
            includeInCards: false
            instructions: 'Select different images per site'
            label: 'Featured Image'
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 510ad4c8-48f8-4726-bc82-0883e5ada07a
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-08T09:21:30+02:00'
            elementCondition: null
            fieldUid: e0cd6b9d-eb8b-4934-8c3d-704ca2f149bb # Secondary Image
            handle: null
            includeInCards: false
            instructions: 'This image will be used on the default page'
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c9bacfd-c529-4dcf-8f7b-abc3a48a663b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-08T09:21:30+02:00'
            elementCondition: null
            fieldUid: 8f7d3ebf-f42d-4024-aeae-1fad436fd93c # Home Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1940a37-f8d1-4445-a880-101255bfabe5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9bbb97bc-bb86-4feb-8333-b532e26b773c
        userCondition: null
handle: home
hasTitleField: true
icon: house
name: Home
showSlugField: true
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: language
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: language
