color: null
fieldLayouts:
  73ac25bc-ace9-4aa6-ba1d-9211b5c06027:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-27T11:43:04+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7582d0fb-761c-473d-8120-b34cf2cd2957
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-27T11:43:04+01:00'
            elementCondition: null
            fieldUid: 735b5e6e-8026-4de4-8e32-14e03d975565 # Content Image
            handle: contentImage
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9b2074e-9c0c-42ca-912b-da62df8b651a
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-12-27T11:43:04+01:00'
            elementCondition: null
            fieldUid: 8cdefc82-9e0e-4dae-8feb-1609c6c9873b # Single Line Text
            handle: caption
            includeInCards: true
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c197fdb4-93bc-4816-98a5-f6703ec33f04
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-27T11:43:04+01:00'
            elementCondition: null
            fieldUid: 503ce48e-30a9-4ab1-9dd4-89fec70a385c # Image Style
            handle: null
            includeInCards: false
            instructions: null
            label: Style
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2dbe0c8-d8a4-48cc-b4ba-082ee622ac0b
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: c7f52bda-4083-406b-982c-63def615500a
        userCondition: null
handle: image
hasTitleField: false
icon: image
name: Image
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
