color: null
fieldLayouts:
  73ac25bc-ace9-4aa6-ba1d-9211b5c06027:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 735b5e6e-8026-4de4-8e32-14e03d975565
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9b2074e-9c0c-42ca-912b-da62df8b651a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: fd670a04-b06c-4830-b8d0-5e2d388ce9a1
            handle: null
            includeInCards: true
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a0ff308-aab3-40f3-9e76-e651b423ca1c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 503ce48e-30a9-4ab1-9dd4-89fec70a385c
            handle: null
            includeInCards: false
            instructions: null
            label: Style
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2dbe0c8-d8a4-48cc-b4ba-082ee622ac0b
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: c7f52bda-4083-406b-982c-63def615500a
        userCondition: null
handle: image
hasTitleField: false
icon: null
name: Image
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
