color: null
fieldLayouts:
  208f5868-6f1a-4491-b819-458390ab267c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-22T16:15:42+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 58ef6845-3579-4299-9662-bd62bbd4d916
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-22T16:15:42+01:00'
            elementCondition: null
            fieldUid: 8cdefc82-9e0e-4dae-8feb-1609c6c9873b # Single Line Text
            handle: heading
            includeInCards: true
            instructions: null
            label: Heading
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39f04409-156b-4380-9baf-0bb62bdc58e4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-22T16:15:42+01:00'
            elementCondition: null
            fieldUid: c7a4af96-920c-42c0-b6d8-202ab522bdab # List Item Image
            handle: null
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3b3d7b8-077b-4b55-acbe-cf00e41d6e00
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-22T16:15:42+01:00'
            elementCondition: null
            fieldUid: 9e2e3c4b-bd17-46b3-97f0-a4f6605b93d9 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b96cf32-f4d5-4f20-ab57-4dec6dcd45ce
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-22T16:15:42+01:00'
            elementCondition: null
            fieldUid: 6e507a59-e39c-49c8-9d8b-2066317bda3f # Location
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b76e2156-27cf-4c02-8556-83d035c86e3e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-22T16:15:42+01:00'
            elementCondition: null
            fieldUid: 164e611f-6177-4d07-a94e-8aaf8395299c # Date and Time
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1eba02c7-3ca9-4e5e-a0f8-53a781379216
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-22T16:15:42+01:00'
            elementCondition: null
            fieldUid: a82ceefa-7dad-42b6-bb96-63b0f115ffdf # External Link
            handle: null
            includeInCards: false
            instructions: null
            label: 'External Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d433292f-8470-42e4-98a1-eeace1ef06b0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 683a12c1-5bbb-47b1-b292-105fd3aaa89e
        userCondition: null
handle: listItem
hasTitleField: false
icon: list-radio
name: 'List Item'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
