color: null
fieldLayouts:
  9993e1fd-6b85-41a5-b5a3-efe51568597e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: be7b43ab-37cd-4a4c-be64-68f6a0a15eb0
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c11856d-7122-4296-b607-943240ccc31e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e7c37b4a-837a-4b30-b183-c2c8d82f92d7
            handle: null
            includeInCards: false
            instructions: null
            label: Attribution
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d64e2481-fc99-4ef5-9e2b-f2153f5d9d20
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 98dc8cd6-5222-4641-8b73-1843c5892502
        userCondition: null
handle: quote
hasTitleField: false
icon: null
name: Quote
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
