color: null
fieldLayouts:
  9993e1fd-6b85-41a5-b5a3-efe51568597e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-05T13:38:59+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b89025db-e0fb-45d1-9399-5202374c32fc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-05T13:38:59+02:00'
            elementCondition: null
            fieldUid: 8cdefc82-9e0e-4dae-8feb-1609c6c9873b # Single Line Text
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4009a7ee-f66d-4d61-9b12-abd9c48fd080
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-05T13:38:59+02:00'
            elementCondition: null
            fieldUid: 8cdefc82-9e0e-4dae-8feb-1609c6c9873b # Single Line Text
            handle: attribution
            includeInCards: false
            instructions: null
            label: Attribution
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 784d5267-5066-42e8-a2ed-a6ad8caa6628
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 98dc8cd6-5222-4641-8b73-1843c5892502
        userCondition: null
handle: quote
hasTitleField: false
icon: quote-right
name: Quote
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
