color: null
fieldLayouts:
  8f3c38b1-65d2-4e00-9f01-7a0da5789184:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-07T10:00:49+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f61d9f33-c8ea-478c-b1d4-f840dc9f1889
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T10:00:49+02:00'
            elementCondition: null
            fieldUid: 489638d6-dd95-43c0-a6cd-cca5a8898feb # Toggle
            handle: wideContent
            includeInCards: false
            instructions: 'Whether this page will use a wider screen size'
            label: 'Wide Content'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d41d64a8-74c7-4a13-b8b2-88461e7b993c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e94737b3-219e-4d83-a1ed-68940100a5b4
        userCondition: null
handle: search
hasTitleField: true
icon: magnifying-glass
name: Search
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: language
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
