allowPublicRegistration: false
deactivateByDefault: false
defaultGroup: ''
photoSubpath: userphotos
photoVolumeUid: 5a0be839-14a2-465e-a504-bb63dd0281e9 # Images
requireEmailVerification: true
validateOnPublicRegistration: false
