altTranslationKeyFormat: null
altTranslationMethod: language
fieldLayouts:
  741edb78-e490-4426-a3ca-1f7033331ddf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-04T01:16:11+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 722dd964-b9a0-4b55-b413-f2954c98c88c
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-12-04T01:16:11+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: true
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: true
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 70f03bf7-40e8-4c9e-8971-deadf35286d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T01:16:11+01:00'
            elementCondition: null
            fieldUid: eb6b24cc-83d7-416f-be4b-d002c7688b58 # Copyright
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7c71e3b-41bf-46f6-920c-4605371cc48e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T01:16:11+01:00'
            elementCondition: null
            template: _cp/related-entries.twig
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: e33ac171-10e4-4be0-ba47-250fbacee9f6
            userCondition: null
            width: 100
        name: Content
        uid: 22529198-b0c8-440f-aa3e-f169a9e3f551
        userCondition: null
fs: $VOLUMES_FS
handle: images
name: Images
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: language
transformFs: $IMAGE_TRANSFORM_FS
transformSubpath: images
