altTranslationKeyFormat: null
altTranslationMethod: language
fieldLayouts:
  6e5b9279-e821-4871-a89d-39660a84f991:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 14bfe0e3-f9d0-439b-9005-0711f136dd25
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 4c320006-d090-4e1e-9c1b-90eb8bbdf53a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 42d432b0-8a0a-4d01-9180-8bad74641bf1
        userCondition: null
fs: $TEMP_IMAGES_FS
handle: tempImages
name: 'Temp Images'
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: language
transformFs: $IMAGE_TRANSFORM_FS
transformSubpath: tempimages
