columnSuffix: uypoopcs
handle: externalLink
instructions: null
name: 'External Link'
searchable: false
settings:
  maxLength: 255
  showLabelField: false
  showTargetField: false
  types:
    - url
translationKeyFormat: null
translationMethod: language
type: craft\fields\Link
