columnSuffix: vaeqrzhy
handle: imageStyle
instructions: null
name: 'Image Style'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Wide (XL screens only)'
        -
          - value
          - wide
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
