columnSuffix: mmhwiovg
contentColumnType: boolean
handle: increaseFontSize
instructions: 'Check if letters are not readable for the selected language'
name: 'Increase Font Size'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: language
type: craft\fields\Lightswitch
