columnSuffix: yvfuijly
handle: siteName
instructions: null
name: 'Site Name'
searchable: false
settings:
  byteLimit: null
  charLimit: 30
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: "{{ object.site.handle|split('_')[1] in ['he', 'ja', 'zh'] ? object.site.handle|split('_')[1] : 'latin' }}"
translationMethod: custom
type: craft\fields\PlainText
