columnSuffix: null
contentColumnType: string
fieldGroup: bd76fb6e-8765-41d3-8e8a-02e37e127c80 # Common
handle: topics
instructions: null
name: Topics
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: 1
  selectionLabel: 'Add a topic'
  showSiteMenu: false
  sources:
    - 'section:599c71b9-f295-4a4d-b1c3-7792f4da3dd6' # Topic
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
