columnSuffix: null
handle: topics
instructions: null
name: Topics
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: 1
  selectionLabel: 'Add a topic'
  showCardsInGrid: true
  showSiteMenu: false
  sources:
    - 'section:599c71b9-f295-4a4d-b1c3-7792f4da3dd6' # Topic
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
