columnSuffix: qgffqhpd
contentColumnType: boolean
handle: wideContent
instructions: 'Whether this page will use in a wider screen size'
name: 'Wide Content'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
