assets:
  tempVolumeUid: ed627edd-73bd-4b75-8684-f410bf4e4b9d # Temp Images
dateModified: 1702426073
elementSources:
  craft\elements\Asset:
    -
      heading: Site
      type: heading
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
      tableAttributes:
        - 'field:cc3fbab0-826f-4aed-b2aa-eeaecc2964bf' # Alt Text
        - imageSize
        - dateModified
        - link
      type: native
    -
      heading: Internal
      type: heading
    -
      disabled: false
      key: 'volume:ed627edd-73bd-4b75-8684-f410bf4e4b9d' # Temp Images
      tableAttributes:
        - 'field:cc3fbab0-826f-4aed-b2aa-eeaecc2964bf' # Alt Text
        - imageSize
        - dateModified
        - link
      type: native
    -
      disabled: false
      key: 'volume:3b60e4f9-36bb-4456-bee5-67160b5a3108' # User Photos
      tableAttributes:
        - 'field:cc3fbab0-826f-4aed-b2aa-eeaecc2964bf' # Alt Text
        - imageSize
        - dateModified
        - link
      type: native
    -
      heading: Work
      type: heading
    -
      condition:
        class: craft\elements\conditions\assets\AssetCondition
        conditionRules:
          -
            class: craft\fields\conditions\TextFieldConditionRule
            fieldUid: cc3fbab0-826f-4aed-b2aa-eeaecc2964bf # Alt Text
            operator: empty
            uid: 8bdb60d1-3489-4d35-b037-93f42b1ba2c4
            value: ''
        elementType: craft\elements\Asset
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:45fca0e3-5d6e-49eb-8303-d97ff1cc88d5'
      label: 'Missing alt text'
      tableAttributes:
        - location
      type: custom
    -
      heading: 'Search & Filter'
      type: heading
    -
      condition:
        class: craft\elements\conditions\assets\AssetCondition
        conditionRules:
          -
            class: craft\elements\conditions\assets\FileTypeConditionRule
            operator: in
            uid: 625c2965-8ee2-4153-8256-eb4de1236834
            values:
              - image
          -
            class: craft\elements\conditions\assets\VolumeConditionRule
            operator: in
            uid: 28c23172-4c68-4ab1-bf09-93b5f4284deb
            values:
              - 5a0be839-14a2-465e-a504-bb63dd0281e9 # Images
        elementType: craft\elements\Asset
        fieldContext: global
      defaultSort:
        - dateCreated
        - desc
      key: 'custom:6a25bb05-b06f-4d56-b1c8-769e3deea72f'
      label: Images
      tableAttributes:
        - imageSize
        - location
        - dateCreated
        - link
      type: custom
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - link
      type: native
    -
      heading: 'Site group specific'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:7a045fb7-ed74-4c72-8482-fc700ab663ca' # Article
      tableAttributes:
        - 'field:7df417e8-1eea-46d8-85a7-2a20370a881e' # Featured Image
        - drafts
        - postDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:fde6b0e6-02b7-426c-9600-7c39eaf0a485' # Location
      tableAttributes:
        - 'field:7df417e8-1eea-46d8-85a7-2a20370a881e' # Featured Image
        - 'field:9acad709-b05a-4ba4-a090-8c7855d52875' # Address
        - link
      type: native
    -
      heading: 'All sites'
      type: heading
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: singles
      tableAttributes:
        - section
        - drafts
        - 'field:7df417e8-1eea-46d8-85a7-2a20370a881e' # Featured Image
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
      tableAttributes:
        - drafts
        - type
        - 'field:7df417e8-1eea-46d8-85a7-2a20370a881e' # Featured Image
        - postDate
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:599c71b9-f295-4a4d-b1c3-7792f4da3dd6' # Topic
      tableAttributes:
        - 'field:7df417e8-1eea-46d8-85a7-2a20370a881e' # Featured Image
        - postDate
        - author
        - link
      type: native
    -
      heading: Work
      type: heading
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\fields\conditions\LightswitchFieldConditionRule
            fieldUid: e708fcd6-e624-4bca-803c-34ab069e72ed # Featured
            uid: 731276c2-ed86-49a4-8fb2-8980997adb2d
            value: true
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 6bbd9b7f-3033-409f-9dd3-b27586840f2d
            values:
              - 7a045fb7-ed74-4c72-8482-fc700ab663ca # Article
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:00f507c2-b782-472d-b85c-f87355d9f487'
      label: 'Featured Articles'
      tableAttributes:
        - 'field:7df417e8-1eea-46d8-85a7-2a20370a881e' # Featured Image
        - author
        - postDate
        - link
      type: custom
email:
  fromEmail: $EMAIL_ADDRESS
  fromName: $EMAIL_SENDER
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: $SMTP_ENCRYPTION_METHOD
    host: $SMTP_HOST
    password: $SMTP_PASSWORD
    port: $SMTP_PORT
    timeout: '10'
    useAuthentication: $SMTP_AUTHENTICATION
    username: $SMTP_USER
  transportType: craft\mail\transportadapters\Smtp
fs:
  imagesTransforms_local:
    hasUrls: true
    name: 'Images Transforms Local'
    settings:
      path: '@webroot/assets/transforms'
    type: craft\fs\Local
    url: '@web/assets/transforms'
  images_local:
    hasUrls: true
    name: 'Images Local'
    settings:
      path: '@webroot/files/images'
    type: craft\fs\Local
    url: '@web/files/images'
  tempimages_local:
    hasUrls: true
    name: 'Temp Images Local'
    settings:
      path: '@webroot/files/temp'
    type: craft\fs\Local
    url: '@web/files/temp'
  userPhotos_local:
    hasUrls: true
    name: 'User Photos Local'
    settings:
      path: '@webroot/files/userphotos'
    type: craft\fs\Local
    url: '@web/files/userphotos'
meta:
  __names__:
    1a974179-ff63-42af-9f2f-b2c34cbfefe2: Munich # Munich
    1e1a1488-33d1-46dd-91d6-f7d1a7ef1434: Default # Default
    1efc3da2-ad70-455b-8d5a-4f712d3e3482: 'Berlin Türkçe' # Berlin Türkçe
    3b60e4f9-36bb-4456-bee5-67160b5a3108: 'User Photos' # User Photos
    3bb09a1c-cb36-438e-b8d5-0b35b0965f4e: Berlin # Berlin
    3c3640d4-1332-4e1a-8745-aab9d3646d81: 'Articles Index' # Articles Index
    3e35a043-a62e-4ede-acd6-44dfb92d6914: 'Site Name' # Site Name
    4b050685-0425-4094-bde2-85e2eedd0e12: Text # Text
    5a0be839-14a2-465e-a504-bb63dd0281e9: Images # Images
    5b0c38db-9ab4-47d8-b4a7-913710c08ca6: 'Berlin English' # Berlin English
    6e507a59-e39c-49c8-9d8b-2066317bda3f: Location # Location
    6ef5e992-55f6-464f-b946-3eda031693df: Hamburg # Hamburg
    7a045fb7-ed74-4c72-8482-fc700ab663ca: Article # Article
    7d425fdf-837b-4d9d-8aa4-8b55fa3a4d82: Search # Search
    7df417e8-1eea-46d8-85a7-2a20370a881e: 'Featured Image' # Featured Image
    8f7d3ebf-f42d-4024-aeae-1fad436fd93c: 'Home Text' # Home Text
    8fc13168-aa9d-4e4b-9754-de59335df6b3: Icon # Icon
    9acad709-b05a-4ba4-a090-8c7855d52875: Address # Address
    9e2e3c4b-bd17-46b3-97f0-a4f6605b93d9: Text # Text
    9e8a3f1b-ec7c-4c9a-9971-b65428c62592: 'Site Info - Global Settings' # Site Info - Global Settings
    9eab0798-59cc-46ce-b621-7f5fbca4ac01: 'Monaco Italiano' # Monaco Italiano
    30cfb989-f158-4630-9bde-19f468e9519c: 'Wide Content' # Wide Content
    033dce53-e320-4834-8bd9-1e93b951e37f: 'Topics Index' # Topics Index
    34c4b5cc-4b07-4d8f-a7fb-c6fbdb96df58: 'Berlin Japanese' # Berlin Japanese
    74bdc2b4-7971-4bf7-ae69-c90f54f03c60: 'Soltau Deutsch' # Soltau Deutsch
    81e6a0d6-13c5-47ad-a9e6-c2181276db9c: Text # Text
    84b98802-2548-4aed-b67e-fc97f6ed9e30: Page # Page
    087d6426-bc8d-4c44-b207-23dd11d11345: Topics # Topics
    92db4484-152c-44ee-9d3f-b7629d555e5f: Default # Default
    164e611f-6177-4d07-a94e-8aaf8395299c: 'Date and Time' # Date and Time
    169ccd00-9c12-4921-b187-8ef8ca2ad525: Assets # Assets
    171bbc5b-3ff0-4585-b77f-7b428f9e1bb4: 'Default Home' # Default Home
    315bfd90-74a8-4b2a-acd2-f32b780c71cb: Default # Default
    503ce48e-30a9-4ab1-9dd4-89fec70a385c: Style # Style
    574daf56-8e00-42e1-9bcb-23461245101f: Soltau # Soltau
    599c71b9-f295-4a4d-b1c3-7792f4da3dd6: Topic # Topic
    733a21de-d87c-45c5-9a67-c91c5a3f6172: 'Munich Hebrew' # Munich Hebrew
    735b5e6e-8026-4de4-8e32-14e03d975565: Image # Image
    992f51d0-e22b-4c12-a6ba-d098fa334cd3: 'Related Entries' # Related Entries
    1181b464-1dd8-415e-86a1-422a8df582d0: 'Default Deutsch' # Default Deutsch
    1370f3ef-a65e-4f13-9c07-179883d907a1: 'Hamburg English' # Hamburg English
    2851da1e-d7d6-4f6a-b680-f283538923f2: 'Default Home' # Default Home
    6856c92d-c593-4425-8886-27e609d74667: Home # Home
    3711281e-d315-423d-a4b3-73aecdb65eac: 'List Item' # List Item
    6293568b-45d8-41e5-a79e-9c084dc06cd3: 'München Deutsch' # München Deutsch
    65355561-253f-4578-abb7-0e27ed694878: 'Berlin Deutsch' # Berlin Deutsch
    69164545-5879-454d-a57e-f703ca431331: Image # Image
    85898001-9c9c-4d46-abf9-a928e44f0d48: 'Body Content' # Body Content
    a00e6fe6-6460-422d-b845-67c760aa1651: Level # Level
    a75bc4db-f149-453d-9972-1c3685ec1b1d: 'Featured Image By Site' # Featured Image By Site
    a82ceefa-7dad-42b6-bb96-63b0f115ffdf: 'External Link' # External Link
    a599f4be-6dfc-4e41-a635-772762da5abe: 'Hamburg Chinese' # Hamburg Chinese
    abefa0bd-6b36-4b4f-a9de-a4304e7b66a3: 'Public Schema' # Public Schema
    ac457f93-1a50-473e-9983-a899a7f0bed7: Heading # Heading
    b4d80b0f-48b3-4b07-a046-5008ae50f05e: Default # Default
    ba328fdf-594b-42f5-b083-3b55765dd8ef: Heading # Heading
    bd76fb6e-8765-41d3-8e8a-02e37e127c80: Common # Common
    be7b43ab-37cd-4a4c-be64-68f6a0a15eb0: Text # Text
    c7a4af96-920c-42c0-b6d8-202ab522bdab: Image # Image
    c780bb7a-337c-46ba-95c4-c0dcbfcb457d: Home # Home
    cc3fbab0-826f-4aed-b2aa-eeaecc2964bf: 'Alt Text' # Alt Text
    cc5167a2-3fc7-4600-bcef-c928500a7155: 'Hamburg Deutsch' # Hamburg Deutsch
    cee9ebb3-ce52-4a35-9a98-0ff3c43853a7: Text # Text
    d6f6663f-190b-40ff-b18b-36267fcf71f6: 'Site Info - Global Settings' # Site Info - Global Settings
    d2620d92-1e9a-4bd4-b474-5a73547f43c9: 'Increase Font Size' # Increase Font Size
    d50026f3-a236-4ae2-b00a-af55076acd17: Site # Site
    da7ce2e3-54b0-43df-9798-32a617f8b887: Quote # Quote
    e0cd6b9d-eb8b-4934-8c3d-704ca2f149bb: 'Secondary Image' # Secondary Image
    e7c37b4a-837a-4b30-b183-c2c8d82f92d7: Attribution # Attribution
    e708fcd6-e624-4bca-803c-34ab069e72ed: Featured # Featured
    eb6b24cc-83d7-416f-be4b-d002c7688b58: Copyright # Copyright
    eb3278b0-e772-48a7-84b6-fae65d958234: 'Locations Index' # Locations Index
    ed627edd-73bd-4b75-8684-f410bf4e4b9d: 'Temp Images' # Temp Images
    f0cfaa93-fb17-46e7-aeff-cc02cf25aeee: 'Munich English' # Munich English
    fbf00eb2-4a16-40ca-96bb-3fadd2bf459c: Default # Default
    fd670a04-b06c-4830-b8d0-5e2d388ce9a1: Caption # Caption
    fde6b0e6-02b7-426c-9600-7c39eaf0a485: Location # Location
plugins:
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: $SYSTEM_NAME
  retryDuration: 30
  schemaVersion: 4.5.3.0
  timeZone: $SYSTEM_TIMEZONE
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: ''
  photoSubpath: null
  photoVolumeUid: 3b60e4f9-36bb-4456-bee5-67160b5a3108 # User Photos
  requireEmailVerification: true
  validateOnPublicRegistration: false
