defaultPlacement: end
enableVersioning: true
entryTypes:
  - 171bbc5b-3ff0-4585-b77f-7b428f9e1bb4 # Default Site Home
handle: defaultHome
maxAuthors: 1
name: 'Default Home'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  1181b464-1dd8-415e-86a1-422a8df582d0: # Default Deutsch
    enabledByDefault: true
    hasUrls: true
    template: _sections/default
    uriFormat: __home__
type: single
