defaultPlacement: end
enableVersioning: true
entryTypes:
  - d6f6663f-190b-40ff-b18b-36267fcf71f6 # Site Info - Global Settings
handle: siteInfo
maxAuthors: 1
name: 'Site Info - Global Settings'
propagationMethod: all
siteSettings:
  1efc3da2-ad70-455b-8d5a-4f712d3e3482: # Berlin Türkçe
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  5b0c38db-9ab4-47d8-b4a7-913710c08ca6: # Berlin English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  9eab0798-59cc-46ce-b621-7f5fbca4ac01: # Monaco Italiano
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  34c4b5cc-4b07-4d8f-a7fb-c6fbdb96df58: # Berlin Japanese
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  74bdc2b4-7971-4bf7-ae69-c90f54f03c60: # Soltau Deutsch
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  733a21de-d87c-45c5-9a67-c91c5a3f6172: # Munich Hebrew
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  1181b464-1dd8-415e-86a1-422a8df582d0: # Default Deutsch
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  1370f3ef-a65e-4f13-9c07-179883d907a1: # Hamburg English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  6293568b-45d8-41e5-a79e-9c084dc06cd3: # München Deutsch
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  65355561-253f-4578-abb7-0e27ed694878: # Berlin Deutsch
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  a599f4be-6dfc-4e41-a635-772762da5abe: # Hamburg Chinese
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  cc5167a2-3fc7-4600-bcef-c928500a7155: # Hamburg Deutsch
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  f0cfaa93-fb17-46e7-aeff-cc02cf25aeee: # Munich English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
